name: first-workflow
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: clone the project
        uses: actions/checkout@v6
      - name: install deps
        run: npm ci
      - name: lint the project
        run: npm run lint
      - name: test the project
        run: npm run test
      - name: build the project
        run: eval "$(npm run dev) Project building"
